CREATE TABLE [dbo].[User]
(
	[UserID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [UserName] NVARCHAR(50) NOT NULL, 
    [Password] NVARCHAR(255) NOT NULL, 
    [Email] NVARCHAR(100) NOT NULL, 
    [Joined] DATETIME NOT NULL, 
    [LastLogin] DATETIME NOT NULL 
)
